### PR TITLE
Fix to add `MapFunction` type back

### LINKED ISSUE #6: unist-util-map types Node and MapFunction stopped to be exported between v3 and v3.1.1
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unist-util-map 3.1.1

### Link to runnable example

https://stackblitz.com/edit/typescript-gjwbvb?file=index.ts

### Steps to reproduce

Start a new sandbox and install the latest `unist-util-map` v3.1.1:
https://stackblitz.com/edit/typescript-gjwbvb?file=index.ts
notice the `MapFunction` and `Node` (and `Parent`) types are not exported any more

but they used to be exported on v3:
https://stackblitz.com/edit/typescript-qh1hrn?file=index.ts

which means, we introduced a **breaking semver change** during a minor bump!

Now, other consumers such as `remark-directive-rehype` are importing the `unist-util-map` with a caret semver, which causes them to break on fresh installs ([stale lockfiles](https://github.com/IGassmann/remark-directive-rehype/blob/5dec9b98dcf8e071d2bd5b776f96123f459492f9/yarn.lock#L472) still contain working v3 references, so everything seems fine for those who have stale lockfiles and their package manager uses exact stale version v3)
https://github.com/IGassmann/remark-directive-rehype/blob/5dec9b98dcf8e071d2bd5b776f96123f459492f9/package.json#L34

### Expected behavior

Let's restore the old type exports, specifically:

```
export type Node = import('unist').Node
export type Parent = import('unist').Parent
export type MapFunction = (node: Node, index?: number, parent?: Parent) => Node
```

If we really want to remove the types, then issue a patch with types restored and bump the major version, publishing this program with types removed.

Generally, to prevent mishaps like this, it's best to migrate the source to `.ts` source files and let the TypeScript generate the types automatically, using a bundler. The JSDoc can be used for examples etc but not as a source of type definitions. That's the setup I use myself, I use `esbuild` to bundle ESM (and sometimes optionally IIFE too) and `rollup` with `rollup-plugin-dts` to bundle up the type definition files. The JSDoc-based types from `.js` sources are a liability.

### Actual behavior

type exports are missing currently

### Affected runtime and version

n/a

### Affected package manager and version

tested on both yarn and npm

### Affected OS and version

n/a

### Build and bundle tools

Other (please specify in steps to reproduce)

### PR DESCRIPTION
**Pull request by JounQin**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

close #6

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -46,6 +46,12 @@ test('unist-util-map', function (t) {
     'should work when passing an empty object'
   )
 
+  t.deepEqual(
+    map(u('root', [u('node', [u('leaf', '1')]), u('leaf', '2')]), asIs),
+    u('root', [u('node', [u('leaf', '1')]), u('leaf', '2')]),
+    'should keep node as-is'
+  )
+
```
Comment (ChristianMurphy) [inline test.js]: I'm not sure I follow how this change relates to adding the `Parent` or `MapFunction` back?

**Review by ChristianMurphy — COMMENTED** [review]
Thanks @JounQin!
Code looks fine, it may be worth waiting for a resolution on https://github.com/syntax-tree/unist-util-map/issues/6#issuecomment-1257203716 before moving forward with this.

File: test.js (hunk 1 above)
Comment (JounQin) [reply test.js]: I need to add a test case to ensure [`asIs`](https://github.com/syntax-tree/unist-util-map/pull/7/files#diff-13876b4beb64b9f156474dc78f9c923952a7ca210d4507b6b3135bbe244f8a60R79-R84) function is used so that eslint with not complain `no-unused-var`.

File: index.js [hunk 2]
```diff
@@ -1,5 +1,11 @@
 /**
  * @typedef {import('unist').Node} Node
+ * @typedef {import('unist').Parent} Parent
```
Comment (wooorm) [inline index.js]: I think parent should be removed.

File: index.js [hunk 3]
```diff
@@ -1,5 +1,11 @@
...
+ */
+
+/**
+ * @template {Node} [T = Node]
```
Comment (wooorm) [inline index.js]:
```suggestion
 * @template {Node} [Tree=Node]
```

Full name to clarify what this type is: you can pass a single node, not an enumeration of nodes.

File: index.js [hunk 4]
```diff
@@ -1,5 +1,11 @@
...
+ * @typedef {import('./complex-types.js').MapFunction<T>} MapFunction<T>
```
Comment (wooorm) [inline index.js]:
```suggestion
 * @typedef {import('./complex-types.js').MapFunction<Tree>} MapFunction
 *   Function called with a node, its index, and its parent to produce a new
 *   node.
```

Some docs.

I tested, and the `<T>` / `<Tree>` at the end *is not used*: it’s output as a comment in the `index.d.ts` file. The `@template` above already does it.

File: test.js (hunk 1 above)
Comment (wooorm) [inline test.js]:
```suggestion
  /** @type {Root} */
  const tree = u('root', [u('node', [u('leaf', '1')]), u('leaf', '2')])

  t.deepEqual(
    map(tree, asIs),
    tree,
    'should support an explicitly typed `MapFunction`'
  )

```

1. By passing an explicit `Root`, TS knows that it’s explicitly that type, otherwise it has to “fit” an object literal into that shape later.
2. Improved message

File: test.js [hunk 5]
```diff
@@ -69,4 +75,11 @@ test('unist-util-map', function (t) {
   function addValue() {
     return {value: 'test'}
   }
+
+  /**
+   * @type {import('./index.js').MapFunction<AnyNode>}
```
Comment (wooorm) [inline test.js]:
```suggestion
   * @type {import('./index.js').MapFunction<Root>}
```

The type parameter to `map` can be a single root node. `MapFunction` infers which children are in that tree.

**Review by wooorm — COMMENTED** [review]
Cool that this works from an `index.js`. I didn’t know that.

Can you remove ~~from `unist-util-map/complex-types.d.ts`~~ in the readme as well?

For later, optional improvements:
- [This line](https://github.com/syntax-tree/unist-util-map/blob/90e8d938e8ff8a72458ffe637122e68b3129b173/complex-types.d.ts#L22) should be `parent: Extract<InclusiveDescendant<Tree>, Parent> | undefined` I think!
- Actual tests for the generics might be useful, such as of like this: https://github.com/syntax-tree/unist-util-filter/blob/main/index.test-d.ts

File: index.js (hunk 2 above)
Comment (JounQin) [reply index.js]:
```suggestion
```

**Comment by JounQin** [comment]
> For later, optional improvements

1. I'm not familiar with that part, so another PR can be raised for it.
2. The `asIs` mapper with `import('./index.js').MapFunction<Root>` alreay tests part of it, but sure a `index.test-d.ts` will be much better.

**Review by wooorm — COMMENTED** [review]
Thanks for your hard work! Looks good to me, *if* other people think it’s fine to add TS 4.5+ syntax: https://github.com/syntax-tree/unist-util-map/issues/6#issuecomment-1259871690

**Review by remcohaszing — APPROVED** [review]
I think it's good to try and stick to the [DefinitelyTyped support window](https://github.com/DefinitelyTyped/DefinitelyTyped#support-window) (unless it's really inconvenient). However, I believe this only requires TypeScript 4.5 to build the types from JSDoc right? Since the types can still be consumed using the same TypeScript versions, it's non-breaking.

**Review by ChristianMurphy — APPROVED** [review]

**Comment by wooorm** [comment]
@remcohaszing i was thinking that first, but without skipLibCheck, I was thinking maybe they'd get checked anyway?
Maybe you're right, and if that's the case then it's especially fine!

**Comment by remcohaszing** [comment]
Nope, TypeScript only looks at the `.d.ts` files. It's the whole reason we build them 😅

**Comment by wooorm** [comment]
Released in [3.1.2](https://github.com/syntax-tree/unist-util-map/releases/tag/3.1.2)! Thanks @JounQin!
